#????????
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bills?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 958824
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validationQuery: SELECT 'x'   #????
      enable: true
      #????
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 958824
        allow:
        deny:
        url-pattern: /druid/*
  #thymeleaf???
  thymeleaf:
    cache: false
    enabled: true
  #      web-stat-filter:
  #        enabled: true
  #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  mvc:
#    format:
#      date-time: yyyy-MM-dd HH:mm:ss
#??mybatisplus
mybatis-plus:
  mapper-locations:
    - classpath:com/fc/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
